const countiesSelect = [
    { value: "CO", label: "Colombia", callsign: "+57" },
    { value: "US", label: "Estados Unidos", callsign: "+1" },
    { value: "EC", label: "Ecuuador", callsign: "+593" },
    { value: "MX", label: "México", callsign: "+52" },
    { value: "PE", label: "Perú", callsign: "+51" },
    { value: "DO", label: "República Dominicana", callsign: "+1-809" },
    { value: "VE", label: "Venezuela", callsign: "+58" },
    { value: "AF", label: "Afganistán", callsign: "+93" },
    { value: "AL", label: "Albania", callsign: "+355" },
    { value: "DE", label: "Alemania", callsign: "+49" },
    { value: "AD", label: "Andorra", callsign: "+376" },
    { value: "AO", label: "Angola", callsign: "+244" },
    { value: "AG", label: "Antigua y Barbuda", callsign: "+1-268" },
    { value: "SA", label: "Arabia Saudita", callsign: "+966" },
    { value: "AR", label: "Argentina", callsign: "+54" },
    { value: "AM", label: "Armenia", callsign: "+374" },
    { value: "AU", label: "Australia", callsign: "+61" },
    { value: "AT", label: "Austria", callsign: "+43" },
    { value: "AZ", label: "Azerbaiyán", callsign: "+994" },
    { value: "BS", label: "Bahamas", callsign: "+1-242" },
    { value: "BH", label: "Baréin", callsign: "+973" },
    { value: "BD", label: "Bangladesh", callsign: "+880" },
    { value: "BB", label: "Barbados", callsign: "+1-246" },
    { value: "BE", label: "Bélgica", callsign: "+32" },
    { value: "BZ", label: "Belice", callsign: "+501" },
    { value: "BJ", label: "Benín", callsign: "+229" },
    { value: "BY", label: "Bielorrusia", callsign: "+375" },
    { value: "BT", label: "Bután", callsign: "+975" },
    { value: "BO", label: "Bolivia", callsign: "+591" },
    { value: "BA", label: "Bosnia y Herzegovina", callsign: "+387" },
    { value: "BW", label: "Botsuana", callsign: "+267" },
    { value: "BR", label: "Brasil", callsign: "+55" },
    { value: "BN", label: "Brunéi", callsign: "+673" },
    { value: "BG", label: "Bulgaria", callsign: "+359" },
    { value: "BF", label: "Burkina Faso", callsign: "+226" },
    { value: "BI", label: "Burundi", callsign: "+257" },
    { value: "CV", label: "Cabo Verde", callsign: "+238" },
    { value: "KH", label: "Camboya", callsign: "+855" },
    { value: "CM", label: "Camerún", callsign: "+237" },
    { value: "CA", label: "Canadá", callsign: "+1" },
    { value: "QA", label: "Catar", callsign: "+974" },
    { value: "CL", label: "Chile", callsign: "+56" },
    { value: "CN", label: "China", callsign: "+86" },
    { value: "CY", label: "Chipre", callsign: "+357" },
    { value: "VA", label: "Ciudad del Vaticano", callsign: "+39" },
    { value: "CI", label: "Costa de Marfil", callsign: "+225" },
    { value: "KM", label: "Comoras", callsign: "+269" },
    { value: "CR", label: "Costa Rica", callsign: "+506" },
    { value: "HR", label: "Croacia", callsign: "+385" },
    { value: "CU", label: "Cuba", callsign: "+53" },
    { value: "DK", label: "Dinamarca", callsign: "+45" },
    { value: "DM", label: "Dominica", callsign: "+1-767" },
    { value: "EG", label: "Egipto", callsign: "+20" },
    { value: "SV", label: "El Salvador", callsign: "+503" },
    { value: "AE", label: "Emiratos Árabes Unidos", callsign: "+971" },
    { value: "ER", label: "Eritrea", callsign: "+291" },
    { value: "SK", label: "Eslovaquia", callsign: "+421" },
    { value: "SI", label: "Eslovenia", callsign: "+386" },
    { value: "ES", label: "España", callsign: "+34" },
    { value: "EE", label: "Estonia", callsign: "+372" },
    { value: "ET", label: "Etiopía", callsign: "+251" },
    { value: "PH", label: "Filipinas", callsign: "+63" },
    { value: "FJ", label: "Fiyi", callsign: "+679" },
    { value: "FI", label: "Finlandia", callsign: "+358" },
    { value: "FR", label: "Francia", callsign: "+33" },
    { value: "GA", label: "Gabón", callsign: "+241" },
    { value: "GM", label: "Gambia", callsign: "+220" },
    { value: "GE", label: "Georgia", callsign: "+995" },
    { value: "GH", label: "Ghana", callsign: "+233" },
    { value: "GR", label: "Grecia", callsign: "+30" },
    { value: "GD", label: "Granada", callsign: "+1-473" },
    { value: "GT", label: "Guatemala", callsign: "+502" },
    { value: "GN", label: "Guinea", callsign: "+224" },
    { value: "GW", label: "Guinea-Bisáu", callsign: "+245" },
    { value: "GQ", label: "Guinea Ecuatorial", callsign: "+240" },
    { value: "GY", label: "Guyana", callsign: "+592" },
    { value: "HT", label: "Haití", callsign: "+509" },
    { value: "HN", label: "Honduras", callsign: "+504" },
    { value: "HU", label: "Hungría", callsign: "+36" },
    { value: "IN", label: "India", callsign: "+91" },
    { value: "ID", label: "Indonesia", callsign: "+62" },
    { value: "IR", label: "Irán", callsign: "+98" },
    { value: "IQ", label: "Irak", callsign: "+964" },
    { value: "IE", label: "Irlanda", callsign: "+353" },
    { value: "IS", label: "Islandia", callsign: "+354" },
    { value: "CK", label: "Islas Cook", callsign: "+682" },
    { value: "MH", label: "Islas Marshall", callsign: "+692" },
    { value: "SB", label: "Islas Salomón", callsign: "+677" },
    { value: "IL", label: "Israel", callsign: "+972" },
    { value: "IT", label: "Italia", callsign: "+39" },
    { value: "JM", label: "Jamaica", callsign: "+1-876" },
    { value: "JP", label: "Japón", callsign: "+81" },
    { value: "JO", label: "Jordania", callsign: "+962" },
    { value: "KZ", label: "Kazajistán", callsign: "+7" },
    { value: "KE", label: "Kenia", callsign: "+254" },
    { value: "KG", label: "Kirgistán", callsign: "+996" },
    { value: "KI", label: "Kiribati", callsign: "+686" },
    { value: "KW", label: "Kuwait", callsign: "+965" },
    { value: "LA", label: "Laos", callsign: "+856" },
    { value: "LS", label: "Lesoto", callsign: "+266" },
    { value: "LV", label: "Letonia", callsign: "+371" },
    { value: "LB", label: "Líbano", callsign: "+961" },
    { value: "LR", label: "Liberia", callsign: "+231" },
    { value: "LY", label: "Libia", callsign: "+218" },
    { value: "LI", label: "Liechtenstein", callsign: "+423" },
    { value: "LT", label: "Lituania", callsign: "+370" },
    { value: "LU", label: "Luxemburgo", callsign: "+352" },
    { value: "MK", label: "Macedonia del Norte", callsign: "+389" },
    { value: "MG", label: "Madagascar", callsign: "+261" },
    { value: "MW", label: "Malaui", callsign: "+265" },
    { value: "MY", label: "Malasia", callsign: "+60" },
    { value: "MV", label: "Maldivas", callsign: "+960" },
    { value: "ML", label: "Malí", callsign: "+223" },
    { value: "MT", label: "Malta", callsign: "+356" },
    { value: "MA", label: "Marruecos", callsign: "+212" },
    { value: "MU", label: "Mauricio", callsign: "+230" },
    { value: "MR", label: "Mauritania", callsign: "+222" },
    { value: "FM", label: "Micronesia", callsign: "+691" },
    { value: "MD", label: "Moldavia", callsign: "+373" },
    { value: "MC", label: "Mónaco", callsign: "+377" },
    { value: "MN", label: "Mongolia", callsign: "+976" },
    { value: "ME", label: "Montenegro", callsign: "+382" },
    { value: "MZ", label: "Mozambique", callsign: "+258" },
    { value: "NA", label: "Namibia", callsign: "+264" },
    { value: "NR", label: "Nauru", callsign: "+674" },
    { value: "NP", label: "Nepal", callsign: "+977" },
    { value: "NI", label: "Nicaragua", callsign: "+505" },
    { value: "NE", label: "Níger", callsign: "+227" },
    { value: "NG", label: "Nigeria", callsign: "+234" },
    { value: "NO", label: "Noruega", callsign: "+47" },
    { value: "OM", label: "Omán", callsign: "+968" },
    { value: "PK", label: "Pakistán", callsign: "+92" },
    { value: "PW", label: "Palaos", callsign: "+680" },
    { value: "PA", label: "Panamá", callsign: "+507" },
    { value: "PG", label: "Papúa Nueva Guinea", callsign: "+675" },
    { value: "PY", label: "Paraguay", callsign: "+595" },
    { value: "PL", label: "Polonia", callsign: "+48" },
    { value: "PT", label: "Portugal", callsign: "+351" },
    { value: "GB", label: "Reino Unido", callsign: "+44" },
    { value: "CG", label: "República del Congo", callsign: "+242" },
    { value: "CD", label: "República Democrática del Congo", callsign: "+243" },
    { value: "RW", label: "Ruanda", callsign: "+250" },
    { value: "RO", label: "Rumania", callsign: "+40" },
    { value: "RU", label: "Rusia", callsign: "+7" },
    { value: "WS", label: "Samoa", callsign: "+685" },
    { value: "KN", label: "San Cristóbal y Nieves", callsign: "+1-869" },
    { value: "VC", label: "San Vicente y las Granadinas", callsign: "+1-784" },
    { value: "SM", label: "San Marino", callsign: "+378" },
    { value: "LC", label: "Santa Lucía", callsign: "+1-758" },
    { value: "ST", label: "Santo Tomé y Príncipe", callsign: "+239" },
    { value: "SN", label: "Senegal", callsign: "+221" },
    { value: "RS", label: "Serbia", callsign: "+381" },
    { value: "SC", label: "Seychelles", callsign: "+248" },
    { value: "SL", label: "Sierra Leona", callsign: "+232" },
    { value: "SG", label: "Singapur", callsign: "+65" },
    { value: "SY", label: "Siria", callsign: "+963" },
    { value: "SO", label: "Somalia", callsign: "+252" },
    { value: "ZA", label: "Sudáfrica", callsign: "+27" },
    { value: "SS", label: "Sudán del Sur", callsign: "+211" },
    { value: "LK", label: "Sri Lanka", callsign: "+94" },
    { value: "SD", label: "Sudán", callsign: "+249" },
    { value: "SE", label: "Suecia", callsign: "+46" },
    { value: "CH", label: "Suiza", callsign: "+41" },
    { value: "SR", label: "Surinam", callsign: "+597" },
    { value: "TH", label: "Tailandia", callsign: "+66" },
    { value: "TW", label: "Taiwán", callsign: "+886" },
    { value: "TZ", label: "Tanzania", callsign: "+255" },
    { value: "TJ", label: "Tayikistán", callsign: "+992" },
    { value: "TL", label: "Timor Oriental", callsign: "+670" },
    { value: "TG", label: "Togo", callsign: "+228" },
    { value: "TO", label: "Tonga", callsign: "+676" },
    { value: "TT", label: "Trinidad y Tobago", callsign: "+1-868" },
    { value: "TN", label: "Túnez", callsign: "+216" },
    { value: "TR", label: "Turquía", callsign: "+90" },
    { value: "TM", label: "Turkmenistán", callsign: "+993" },
    { value: "TV", label: "Tuvalu", callsign: "+688" },
    { value: "UA", label: "Ucrania", callsign: "+380" },
    { value: "UG", label: "Uganda", callsign: "+256" },
    { value: "UY", label: "Uruguay", callsign: "+598" },
    { value: "UZ", label: "Uzbekistán", callsign: "+998" },
    { value: "VU", label: "Vanuatu", callsign: "+678" },
    { value: "VN", label: "Vietnam", callsign: "+84" },
    { value: "YE", label: "Yemen", callsign: "+967" },
    { value: "DJ", label: "Yibuti", callsign: "+253" },
    { value: "ZM", label: "Zambia", callsign: "+260" },
    { value: "ZW", label: "Zimbabue", callsign: "+263" },
];

export default countiesSelect;