const departments: { value: string; label: string }[] = [
    { value: 'Bogota D.C.', label: 'Bogotá D.C.' },
    { value: 'Amazonas', label: 'Amazonas' },
    { value: 'Antioquia', label: 'Antioquia' },
    { value: 'Arauca', label: 'Arauca' },
    { value: 'Atlantico', label: 'Atlántico' },
    { value: 'Bolivar', label: 'Bolívar' },
    { value: 'Boyaca', label: 'Boyacá' },
    { value: 'Caldas', label: 'Caldas' },
    { value: 'Caqueta', label: 'Caquetá' },
    { value: 'Casanare', label: 'Casanare' },
    { value: 'Cauca', label: 'Cauca' },
    { value: 'Cesar', label: 'Cesar' },
    { value: 'Choco', label: 'Chocó' },
    { value: 'Cordoba', label: 'Córdoba' },
    { value: 'Cundinamarca', label: 'Cundinamarca' },
    { value: 'Guainia', label: 'Guainía' },
    { value: 'Guaviare', label: 'Guaviare' },
    { value: 'Huila', label: 'Huila' },
    { value: 'La Guajira', label: 'La Guajira' },
    { value: 'Magdalena', label: 'Magdalena' },
    { value: 'Meta', label: 'Meta' },
    { value: 'Nariño', label: 'Nariño' },
    { value: 'Norte de Santander', label: 'Norte de Santander' },
    { value: 'Putumayo', label: 'Putumayo' },
    { value: 'Quindio', label: 'Quindío' },
    { value: 'Risaralda', label: 'Risaralda' },
    { value: 'San Andraes y Providencia', label: 'San Andrés y Providencia' },
    { value: 'Santander', label: 'Santander' },
    { value: 'Sucre', label: 'Sucre' },
    { value: 'Tolima', label: 'Tolima' },
    { value: 'Valle del Cauca', label: 'Valle del Cauca' },
    { value: 'Vaupes', label: 'Vaupés' },
    { value: 'Vichada', label: 'Vichada' },
];

export default departments;