const productManufacturers: { value: string; label: string }[] = [
    { value: 'NINGUN FABRICANTE', label: 'Ningún fabricante' },
    { value: '3M', label: '3M' },
    { value: 'ABB', label: 'ABB' },
    { value: 'ACE ENMARCACIONES Y CARTELERAS', label: 'ACE Enmarcaciones y Carteleras' },
    { value: 'ACE SCHMERSAL', label: 'ACE Schmersal' },
    { value: 'ADLER', label: 'Adler' },
    { value: 'AERESTOP', label: 'Aerestop' },
    { value: 'AERSTOP', label: 'Aerstop' },
    { value: 'AESA', label: 'AESA' },
    { value: 'AFL', label: 'AFL' },
    { value: 'ALBRON', label: 'Albron' },
    { value: 'ALKORAYEF', label: 'Alkorayef' },
    { value: 'ALLEN-BRADLEY', label: 'Allen-Bradley' },
    { value: 'ALPHA TECHNOLOGIES', label: 'Alpha Technologies' },
    { value: 'ALURACK', label: 'Alurack' },
    { value: 'AMCI', label: 'AMCI' },
    { value: 'AMERICAN ELECTRIC LIGHTING', label: 'American Electric Lighting' },
    { value: 'APAR', label: 'Apar' },
    { value: 'APC', label: 'APC' },
    { value: 'APM', label: 'APM' },
    { value: 'APPLETON', label: 'Appleton' },
    { value: 'ARISTONCAVI', label: 'Aristoncavi' },
    { value: 'ARTECH', label: 'Artech' },
    { value: 'ARTISAN CONTROLS', label: 'Artisan Controls' },
    { value: 'AS1', label: 'AS1' },
    { value: 'ASIATICA', label: 'Asiática' },
    { value: 'ASTRAL', label: 'Astral' },
    { value: 'AVE COLOMBIA', label: 'AVE Colombia' },
    { value: 'AWM', label: 'AWM' },
    { value: 'AXIS', label: 'Axis' },
    { value: 'AZUL ENERGY', label: 'Azul Energy' },
    { value: 'BALDOR', label: 'Baldor' },
    { value: 'BALLUF', label: 'Balluf' },
    { value: 'BAND IT', label: 'Band It' },
    { value: 'BARKSDALE', label: 'Barksdale' },
    { value: 'BARTEC', label: 'Bartec' },
    { value: 'BCP', label: 'BCP' },
    { value: 'BELDEN', label: 'Belden' },
    { value: 'BEN TRADE CABLE', label: 'Ben Trade Cable' },
    { value: 'BESTER', label: 'Bester' },
    { value: 'BLOX', label: 'Blox' },
    { value: 'BM', label: 'BM' },
    { value: 'BORNAS Y TERMINALES', label: 'Bornas y Terminales' },
    { value: 'BOSH', label: 'Bosh' },
    { value: 'BRAZIL', label: 'Brazil' },
    { value: 'BREATH TESTER', label: 'Breath Tester' },
    { value: 'BURNDY', label: 'Burndy' },
    { value: 'BUSSMAN', label: 'Bussman' },
    { value: 'C3 CONTROLS', label: 'C3 Controls' },
    { value: 'CA MEJIA &CIA', label: 'CA Mejía &Cía' },
    { value: 'CABLOFIL', label: 'Cablofil' },
    { value: 'CABUR', label: 'Cabur' },
    { value: 'CALORCOL', label: 'Calorcol' },
    { value: 'CALZECOL', label: 'Calzecol' },
    { value: 'CARIBE', label: 'Caribe' },
    { value: 'CARLON', label: 'Carlon' },
    { value: 'CATAMOUNT', label: 'Catamount' },
    { value: 'CBI ELECTRIC', label: 'CBI Electric' },
    { value: 'CE+T POWER', label: 'CE+T Power' },
    { value: 'CELSA', label: 'Celsa' },
    { value: 'CELTA', label: 'Celta' },
    { value: 'CENTELSA', label: 'Centelsa' },
    { value: 'CENTRAL DE TORNILLOS Y REMACHE', label: 'Central de Tornillos y Remache' },
    { value: 'CETA', label: 'Ceta' },
    { value: 'CHANGLAN', label: 'Changlan' },
    { value: 'CHECKLINE', label: 'Checkline' },
    { value: 'CHIKO', label: 'Chiko' },
    { value: 'CHINT', label: 'Chint' },
    { value: 'CICOBRES', label: 'Cicobres' },
    { value: 'CILES', label: 'Ciles' },
    { value: 'CIRPORTEC', label: 'Cirportec' },
    { value: 'CISCO', label: 'Cisco' },
    { value: 'CL', label: 'CL' },
    { value: 'CL INGENIERIA COMERCIAL', label: 'CL Ingeniería Comercial' },
    { value: 'CLESUS', label: 'Clesus' },
    { value: 'CODELCA', label: 'Codelca' },
    { value: 'COFRECOL', label: 'Cofrecol' },
    { value: 'COLCELDAS INGENIERIA', label: 'Colceldas Ingeniería' },
    { value: 'COLCIRCUITOS', label: 'Colcircuitos' },
    { value: 'COLE PARMER', label: 'Cole Parmer' },
    { value: 'COLMENA', label: 'Colmena' },
    { value: 'COLOMBIA INDUCABLES SAS', label: 'Colombia Inducables SAS' },
    { value: 'COLOMBIANA DE BRONCES Y LATONE', label: 'Colombiana de Bronces y Latone' },
    { value: 'COLPILAS', label: 'Colpilas' },
    { value: 'COLWED SAS', label: 'Colwed SAS' },
    { value: 'COMFIT', label: 'Comfit' },
    { value: 'COMMSCOPE', label: 'Commscope' },
    { value: 'COMPAÑIA ELECTRICA', label: 'Compañía Eléctrica' },
    { value: 'COMPAÑÍA PAPELERA', label: 'Compañía Papelera' },
    { value: 'CONALCABLES', label: 'Conalcables' },
    { value: 'CONDUCOL', label: 'Conducol' },
    { value: 'CONDUMEX', label: 'Condumex' },
    { value: 'COOPER', label: 'Cooper' },
    { value: 'CORACERO', label: 'Coracero' },
    { value: 'CORAFLEX', label: 'Coraflex' },
    { value: 'CORMANCOL', label: 'Cormancol' },
    { value: 'CORNING', label: 'Corning' },
    { value: 'COVER', label: 'Cover' },
    { value: 'CRC INDUSTRIAL', label: 'CRC Industrial' },
    { value: 'CRICON', label: 'Cricon' },
    { value: 'CRIOTECH S.A.', label: 'Criotech S.A.' },
    { value: 'CROUSE HINDS', label: 'Crouse Hinds' },
    { value: 'CRYDOM', label: 'Crydom' },
    { value: 'CS-SYSTIMAX', label: 'CS-Systimax' },
    { value: 'CU CONECTORES', label: 'CU Conectores' },
    { value: 'DANFOSS', label: 'Danfoss' },
    { value: 'DAYLIGHT', label: 'Daylight' },
    { value: 'DEHN', label: 'Dehn' },
    { value: 'DEIF', label: 'Deif' },
    { value: 'DELARCO', label: 'Delarco' },
    { value: 'DELGA', label: 'Delga' },
    { value: 'DELHORST', label: 'Delhorst' },
    { value: 'DELTA', label: 'Delta' },
    { value: 'DEWALT', label: 'Dewalt' },
    { value: 'DEXSON', label: 'Dexson' },
    { value: 'DF ELECTRIC', label: 'DF Electric' },
    { value: 'DIALIGHT', label: 'Dialight' },
    { value: 'DIANQUI', label: 'Dianqui' },
    { value: 'DICOL LTDA', label: 'Dicol LTDA' },
    { value: 'DISTRIVAL', label: 'Distrival' },
    { value: 'DUCATI', label: 'Ducati' },
    { value: 'DUNCAN', label: 'Duncan' },
    { value: 'DUPLEX', label: 'Duplex' },
    { value: 'DURMAN', label: 'Durman' },
    { value: 'DUTOTEC', label: 'Dutotec' },
    { value: 'DXPRO', label: 'Dxpro' },
    { value: 'DYMEL', label: 'Dymel' },
    { value: 'DYMINEL', label: 'Dyminel' },
    { value: 'EATON', label: 'Eaton' },
    { value: 'EBCHQ', label: 'EBCHQ' },
    { value: 'EBMPAPST', label: 'EBMPAPST' },
    { value: 'ECI DLC', label: 'ECI DLC' },
    { value: 'EDELWIS', label: 'EDELWIS' },
    { value: 'EDWARDS', label: 'Edwards' },
    { value: 'EFCORLET', label: 'Efcorlet' },
    { value: 'EGA-MASTER', label: 'Ega-Master' },
    { value: 'EL WATTIO', label: 'El Wattio' },
    { value: 'ELECTRICOS INDUSTRIALES NY', label: 'Eléctricos Industriales NY' },
    { value: 'ELECTROCONTROL', label: 'Electrocontrol' },
    { value: 'ELECTROPOL COLOMBIA SAS', label: 'Electropol Colombia SAS' },
    { value: 'ELECTROSILVANIA', label: 'Electrosilvania' },
    { value: 'EMCOCABLES', label: 'Emcocables' },
    { value: 'EMERGENTE', label: 'Emergente' },
    { value: 'EMINCO', label: 'Eminco' },
    { value: 'ENCO', label: 'Enco' },
    { value: 'ENCOFERT', label: 'Encofert' },
    { value: 'ENERGY TECHNOLOGIES', label: 'Energy Technologies' },
    { value: 'ENERLUX', label: 'Enerlux' },
    { value: 'EQUITRONICA', label: 'Equitronica' },
    { value: 'ERC', label: 'ERC' },
    { value: 'ESAB', label: 'Esab' },
    { value: 'ESE', label: 'Ese' },
    { value: 'ESTRUC', label: 'Estruc' },
    { value: 'EUROTEC', label: 'Eurotec' },
    { value: 'EZVIZ', label: 'Ezviz' },
    { value: 'FABRICUR', label: 'Fabricur' },
    { value: 'FACELEC', label: 'Facelec' },
    { value: 'FACOMALLAS', label: 'Facomallas' },
    { value: 'FANOX', label: 'Fanox' },
    { value: 'FASTON', label: 'Faston' },
    { value: 'FAVIGEL', label: 'Favigel' },
    { value: 'FCE', label: 'FCE' },
    { value: 'FEDERAL SIGNAL', label: 'Federal Signal' },
    { value: 'FERROMINERALES', label: 'Ferrominerales' },
    { value: 'FIBRATORE', label: 'Fibratore' },
    { value: 'FINDER', label: 'Finder' },
    { value: 'FLEXILATINA', label: 'Flexilatina' },
    { value: 'FLUKE', label: 'Fluke' },
    { value: 'FUJI', label: 'Fuji' },
    { value: 'FURUKAWA', label: 'Furukawa' },
    { value: 'FUSSAND', label: 'Fussand' },
    { value: 'FUTURE FIBRE TECHNOLOGIES', label: 'Future Fibre Technologies' },
    { value: 'GAMA', label: 'Gama' },
    { value: 'GARLOCK', label: 'Garlock' },
    { value: 'GATU', label: 'Gatu' },
    { value: 'GEMS SENSORS', label: 'Gems Sensors' },
    { value: 'GENERAL CABLE', label: 'General Cable' },
    { value: 'GENERAL ELECTRIC', label: 'General Electric' },
    { value: 'GENERICO', label: 'Generico' },
    { value: 'GERFOR', label: 'Gerfor' },
    { value: 'GIC', label: 'GIC' },
    { value: 'GP-PRO', label: 'GP-PRO' },
    { value: 'GROWATT', label: 'Growatt' },
    { value: 'GRUPO INTELLI', label: 'Grupo Intelli' },
    { value: 'GW-INSTEK', label: 'GW-Instek' },
    { value: 'HAKEL', label: 'Hakel' },
    { value: 'HAMMAR PRODUKTER', label: 'Hammar Produkter' },
    { value: 'HARTING', label: 'Harting' },
    { value: 'HASTINGS', label: 'Hastings' },
    { value: 'HELUKABEL', label: 'Helukabel' },
    { value: 'HENGTONG', label: 'Hengtong' },
    { value: 'HERRAGRO', label: 'Herragro' },
    { value: 'HERRAJES JM', label: 'Herrajes JM' },
    { value: 'HIKVISION', label: 'Hikvision' },
    { value: 'HILTI', label: 'Hilti' },
    { value: 'HIRSCHMANN', label: 'Hirschmann' },
    { value: 'HITACHI', label: 'Hitachi' },
    { value: 'HOFFMAN', label: 'Hoffman' },
    { value: 'HOLOPHANE', label: 'Holophane' },
    { value: 'HONEYWELL', label: 'Honeywell' },
    { value: 'HOUSINGS', label: 'Housings' },
    { value: 'HOYMILES', label: 'Hoymiles' },
    { value: 'HUADONG', label: 'Huadong' },
    { value: 'HUAWEI', label: 'Huawei' },
    { value: 'HUBELL', label: 'Hubbell' },
    { value: 'HYTREX', label: 'Hytrex' },
    { value: 'IDEC', label: 'IDEC' },
    { value: 'IED', label: 'IED' },
    { value: 'IEQ', label: 'IEQ' },
    { value: 'ILUMEC', label: 'Ilumec' },
    { value: 'ILURAM', label: 'Iluram' },
    { value: 'IMEC', label: 'IMEC' },
    { value: 'IMPERIAL', label: 'Imperial' },
    { value: 'INADISA', label: 'Inadisa' },
    { value: 'INDESA', label: 'Indesa' },
    { value: 'INDIA', label: 'India' },
    { value: 'INDUAL', label: 'Indual' },
    { value: 'INDUCABLES', label: 'Inducables' },
    { value: 'INDUMA', label: 'Induma' },
    { value: 'INDUSTRONIC', label: 'Industronic' },
    { value: 'INSAFE', label: 'Insafe' },
    { value: 'INTI', label: 'Inti' },
    { value: 'INTI EX', label: 'Inti Ex' },
    { value: 'IPAC', label: 'IPAC' },
    { value: 'IRWIS', label: 'Irwis' },
    { value: 'IZOLET', label: 'Izolet' },
    { value: 'J PROPSTER', label: 'J Propster' },
    { value: 'JACKSON', label: 'Jackson' },
    { value: 'JAPS', label: 'Japs' },
    { value: 'JINKO', label: 'Jinko' },
    { value: 'JSL MATERIAL ELECTRICO', label: 'JSL Material Eléctrico' },
    { value: 'KAISE', label: 'Kaise' },
    { value: 'KANGARO', label: 'Kangaro' },
    { value: 'KELLEMS', label: 'Kellems' },
    { value: 'KERITE', label: 'Kerite' },
    { value: 'KINGSTON', label: 'Kingston' },
    { value: 'KINSA', label: 'Kinsa' },
    { value: 'KLEMSAN', label: 'Klemsan' },
    { value: 'KOWET', label: 'Kowet' },
    { value: 'KRISTECH', label: 'Kristech' },
    { value: 'KUSSMAUL', label: 'Kussmaul' },
    { value: 'KVOLED', label: 'Kvoled' },
    { value: 'LAKELAND', label: 'Lakeland' },
    { value: 'LAMONS', label: 'Lamons' },
    { value: 'LAPP', label: 'Lapp' },
    { value: 'LEADSUN', label: 'Leadsun' },
    { value: 'LEDTRONICS', label: 'Ledtronics' },
    { value: 'LEGRAND', label: 'Legrand' },
    { value: 'LEOCH', label: 'Leoch' },
    { value: 'LEVELONE', label: 'Levelone' },
    { value: 'LEVITON', label: 'Leviton' },
    { value: 'LIBUS', label: 'Libus' },
    { value: 'LINE KOMBO', label: 'Line Kombo' },
    { value: 'LITHONIA', label: 'Lithonia' },
    { value: 'LITTLEFUSE', label: 'Littlefuse' },
    { value: 'LLOYD INDUSTRIES', label: 'Lloyd Industries' },
    { value: 'LOCTITE', label: 'Loctite' },
    { value: 'LOVAL', label: 'Loval' },
    { value: 'LOVATO', label: 'Lovato' },
    { value: 'LS', label: 'LS' },
    { value: 'LUDA', label: 'Luda' },
    { value: 'LUHFSER', label: 'Luhfser' },
    { value: 'LUMEN', label: 'Lumen' },
    { value: 'MAGNUN DIMENSION', label: 'Magnun Dimension' },
    { value: 'MAKITA', label: 'Makita' },
    { value: 'MANUFACTURAS CAD', label: 'Manufacturas CAD' },
    { value: 'MARECHAL ELECTRIC', label: 'Marechal Electric' },
    { value: 'MARLUVAS', label: 'Marluvas' },
    { value: 'MATRIMOL', label: 'Matrimol' },
    { value: 'MBS', label: 'MBS' },
    { value: 'MCL', label: 'MCL' },
    { value: 'MCR SAFETY', label: 'MCR Safety' },
    { value: 'MCS', label: 'MCS' },
    { value: 'MECANO', label: 'Mecano' },
    { value: 'MEDICABLES', label: 'Medicables' },
    { value: 'MELEC', label: 'Melec' },
    { value: 'MERCOID', label: 'Mercoid' },
    { value: 'MERSEN', label: 'Mersen' },
    { value: 'METAL CORAZA', label: 'Metal Coraza' },
    { value: 'MICROLINK', label: 'Microlink' },
    { value: 'MILLER', label: 'Miller' },
    { value: 'MINERALLAC', label: 'Minerallac' },
    { value: 'MITSUBISHI', label: 'Mitsubishi' },
    { value: 'MOTIONCABLES', label: 'Motioncables' },
    { value: 'MULTIVAPOR', label: 'Multivapor' },
    { value: 'MUNDIAL DE TORNILLOS', label: 'Mundial de Tornillos' },
    { value: 'MYLLER', label: 'Myller' },
    { value: 'N/A', label: 'N/A' },
    { value: 'NACIONAL', label: 'Nacional' },
    { value: 'NATURAL', label: 'Natural' },
    { value: 'NEKCOM', label: 'Nekcom' },
    { value: 'NEODYN', label: 'Neodyn' },
    { value: 'NEWLINE', label: 'Newline' },
    { value: 'NEXANS', label: 'Nexans' },
    { value: 'NICHOLSON', label: 'Nicholson' },
    { value: 'NIUELEC TECHNOLOGY', label: 'NiuElec Technology' },
    { value: 'NO TIENE', label: 'No Tiene' },
    { value: 'NOVA BLANCO', label: 'Nova Blanco' },
    { value: 'O/Z', label: 'O/Z' },
    { value: 'OBO BETTERMAN', label: 'OBO Betterman' },
    { value: 'OMALIGHTING', label: 'OmaLighting' },
    { value: 'OMNION POWER', label: 'Omnion Power' },
    { value: 'OMRON', label: 'Omron' },
    { value: 'ONKA', label: 'Onka' },
    { value: 'OPTEG', label: 'Opteg' },
    { value: 'OPTO 22', label: 'Opto 22' },
    { value: 'OPTRAL', label: 'Optral' },
    { value: 'OSRAM', label: 'Osram' },
    { value: 'OZ', label: 'OZ' },
    { value: 'OZ Gedney', label: 'OZ Gedney' },
    { value: 'PANDUIT', label: 'Panduit' },
    { value: 'PAVCO', label: 'Pavco' },
    { value: 'PELICAN', label: 'Pelican' },
    { value: 'PEMSA', label: 'Pemsa' },
    { value: 'PERALTA', label: 'Peralta' },
    { value: 'PETERCO', label: 'Peterco' },
    { value: 'PHILIPS', label: 'Philips' },
    { value: 'PHOENIX', label: 'Phoenix' },
    { value: 'PINTUCO', label: 'Pintuco' },
    { value: 'PLASTIMEC', label: 'Plastimec' },
    { value: 'PLP', label: 'PLP' },
    { value: 'POLLAK', label: 'Pollak' },
    { value: 'POWEST', label: 'Powest' },
    { value: 'PRETECOR', label: 'Pretecor' },
    { value: 'PRISMALIGHT', label: 'Prismalight' },
    { value: 'PROCABLES', label: 'Procables' },
    { value: 'PROCET SCIENTIFIC', label: 'Procet Scientific' },
    { value: 'PROELÉCTRICOS', label: 'Proeléctricos' },
    { value: 'PROJOY', label: 'Projoy' },
    { value: 'PROLINE', label: 'Proline' },
    { value: 'PROSOFT', label: 'Prosoft' },
    { value: 'PROTECK', label: 'Proteck' },
    { value: 'PROTECONTROL', label: 'Protecontrol' },
    { value: 'PRYSMIAN', label: 'Prysmian' },
    { value: 'PULS', label: 'Puls' },
    { value: 'PYLONTECH', label: 'Pylontech' },
    { value: 'PYTCO', label: 'Pytco' },
    { value: 'QUADRITALIA', label: 'Quadritalia' },
    { value: 'QUEST', label: 'Quest' },
    { value: 'RACOR', label: 'Racor' },
    { value: 'RAEE AMBIENTAL', label: 'Raee Ambiental' },
    { value: 'RAMCRO', label: 'Ramcro' },
    { value: 'RAWELT', label: 'Rawelt' },
    { value: 'RAXTON', label: 'Raxton' },
    { value: 'RAYCHEM', label: 'Raychem' },
    { value: 'REDICTEC', label: 'Redictec' },
    { value: 'REDITEC', label: 'Reditec' },
    { value: 'RELPOL', label: 'Relpol' },
    { value: 'REPL', label: 'Repl' },
    { value: 'REXROTH', label: 'Rexroth' },
    { value: 'RIG-A-LITE', label: 'Rig-A-Lite' },
    { value: 'RITTAL', label: 'Rittal' },
    { value: 'ROSEMOUNT', label: 'Rosemount' },
    { value: 'ROXTEC', label: 'Roxtec' },
    { value: 'ROY ALPHA', label: 'Roy Alpha' },
    { value: 'RYLSA', label: 'Rylsa' },
    { value: 'SAFETY', label: 'Safety' },
    { value: 'SALZER', label: 'Salzer' },
    { value: 'SCHNEIDER', label: 'Schneider' },
    { value: 'SCI', label: 'Sci' },
    { value: 'SCULLY', label: 'Scully' },
    { value: 'SEGWAY', label: 'Segway' },
    { value: 'SELLING', label: 'Selling' },
    { value: 'SEM', label: 'Sem' },
    { value: 'SEMIKRON', label: 'Semikron' },
    { value: 'SEW EURODRIVE', label: 'Sew Eurodrive' },
    { value: 'SHANWMUT', label: 'Shanwmut' },
    { value: 'SHIMADEN', label: 'Shimaden' },
    { value: 'SHOTO', label: 'Shoto' },
    { value: 'SHOW ME CABLES', label: 'Show Me Cables' },
    { value: 'SIBA', label: 'Siba' },
    { value: 'SIEMENS', label: 'Siemens' },
    { value: 'SIEMON', label: 'Siemon' },
    { value: 'SIGMASTEK', label: 'Sigmastek' },
    { value: 'SIKA', label: 'Sika' },
    { value: 'SILVANIA', label: 'Silvania' },
    { value: 'SIMPLEX', label: 'Simplex' },
    { value: 'SIN MARCA', label: 'Sin Marca' },
    { value: 'SISCOAX', label: 'Siscoax' },
    { value: 'SOCOL', label: 'Socol' },
    { value: 'SOLDEXEL', label: 'Soldexel' },
    { value: 'SOUTHWIRE', label: 'Southwire' },
    { value: 'STANLEY', label: 'Stanley' },
    { value: 'STAR ELECTRIC', label: 'Star Electric' },
    { value: 'STECK', label: 'Steck' },
    { value: 'STEELPRO', label: 'Steelpro' },
    { value: 'STEGO', label: 'Stego' },
    { value: 'SUBMER', label: 'Submer' },
    { value: 'SUMCAB', label: 'Sumcab' },
    { value: 'SUMNER', label: 'Sumner' },
    { value: 'SUNNADESIGN', label: 'Sunnadesign' },
    { value: 'SUNRISE', label: 'Sunrise' },
    { value: 'SUNTREE', label: 'Suntree' },
    { value: 'SUPERLOCK', label: 'Superlock' },
    { value: 'SWANGELOG', label: 'Swangelog' },
    { value: 'SWIVELPOLE', label: 'Swivelpole' },
    { value: 'SYLVANIA', label: 'Sylvania' },
    { value: 'TADIRAN', label: 'Tadiran' },
    { value: 'TALLER 84', label: 'Taller 84' },
    { value: 'TB PLUS', label: 'TB Plus' },
    { value: 'TD-WIRE', label: 'TD-Wire' },
    { value: 'TE CONNECTIVITY', label: 'TE Connectivity' },
    { value: 'TECNA', label: 'Tecna' },
    { value: 'TECNOWELD', label: 'Tecnoweld' },
    { value: 'TEGAM`S', label: 'Tegam`s' },
    { value: 'TELDOR', label: 'Teldor' },
    { value: 'TELEMECANIQUE', label: 'Telemecanique' },
    { value: 'TELERGON', label: 'Telergon' },
    { value: 'TENARIS', label: 'Tenaris' },
    { value: 'TESLA', label: 'Tesla' },
    { value: 'THERMOWELD', label: 'Thermoweld' },
    { value: 'THKC', label: 'THKC' },
    { value: 'THOMAS & BETTS', label: 'Thomas & Betts' },
    { value: 'TIPO COLMENA', label: 'Tipo Colmena' },
    { value: 'TITAN', label: 'Titan' },
    { value: 'TJP', label: 'TJP' },
    { value: 'TOOL', label: 'Tool' },
    { value: 'TOP CABLE', label: 'Top Cable' },
    { value: 'TOP DRIVE MONTAJES', label: 'Top Drive Montajes' },
    { value: 'TOP DRIVE SAS', label: 'Top Drive SAS' },
    { value: 'TORNIRAP', label: 'Tornirap' },
    { value: 'TRAMONTINA', label: 'Tramontina' },
    { value: 'TRENCH', label: 'Trench' },
    { value: 'TRENDNET', label: 'Trendnet' },
    { value: 'TRI STATE', label: 'Tri State' },
    { value: 'TRIANRUI', label: 'Trianrui' },
    { value: 'TRITON', label: 'Triton' },
    { value: 'TRUPER', label: 'Truper' },
    { value: 'TUBO-FIX', label: 'Tubo-Fix' },
    { value: 'TUBOSA', label: 'Tubosa' },
    { value: 'ULTRACOLOR', label: 'Ultracolor' },
    { value: 'UNEX', label: 'Unex' },
    { value: 'UNIVERSAL DE CAUCHOS', label: 'Universal de Caucho' },
    { value: 'UTILUX', label: 'Utilux' },
    { value: 'VALFER', label: 'Valfer' },
    { value: 'VCP', label: 'VCP' },
    { value: 'VENTURE LIGHT', label: 'Venture Light' },
    { value: 'VESTA', label: 'Vesta' },
    { value: 'VOLTRONIC', label: 'Voltronic' },
    { value: 'VTA', label: 'VTA' },
    { value: 'WAGO', label: 'Wago' },
    { value: 'WEG', label: 'Weg' },
    { value: 'WEIDMULLER', label: 'Weidmuller' },
    { value: 'WEISZ', label: 'Weisz' },
    { value: 'WESTERN DIGITAL', label: 'Western Digital' },
    { value: 'WIELAND', label: 'Wieland' },
    { value: 'WOER', label: 'Woer' },
    { value: 'XP SAFETY SYSTEM', label: 'XP Safety System' },
    { value: 'YINGLI', label: 'Yingli' },
    { value: 'Y-ONE', label: 'Y-One' },
    { value: 'YONYU', label: 'Yonyu' },
    { value: 'ZCEBOX', label: 'Zcebox' },
    { value: 'ZTT', label: 'Ztt' },
];

export default productManufacturers;