const productsTypes: { value: string; label: string }[] = [
    { value: 'ACOPLAMIENTO', label: 'Acoplamiento' },
    { value: 'ACUSTICA', label: 'Acústica' },
    { value: 'ADAPTADOR', label: 'Adaptador' },
    { value: 'ADSS', label: 'ADSS' },
    { value: 'AISLANTE', label: 'Aislante' },
    { value: 'AMPERIMETRO', label: 'Amperímetro' },
    { value: 'ANALIZADOR DE RED', label: 'Analizador de Red' },
    { value: 'ARMADA', label: 'Armada' },
    { value: 'ARQUITECTONICA', label: 'Arquitectónica' },
    { value: 'ARRANCADOR', label: 'Arrancador' },
    { value: 'AUTOMATICO', label: 'Automático' },
    { value: 'AUTOMATICO ACB', label: 'Automático ACB' },
    { value: 'AUTOMATICO MCCB', label: 'Automático MCCB' },
    { value: 'AUTOSOPORTADO A PRUEBA DE EXPLOSION', label: 'Autosportado a Prueba de Explosión' },
    { value: 'AUTOSOPORTADO EN ACERO INOXIDABLE', label: 'Autosportado en Acero Inoxidable' },
    { value: 'AUTOSOPORTADO EN COLL-ROLLED', label: 'Autosportado en Coll-Rolled' },
    { value: 'AUTOSOPORTADO EN POLIMERO', label: 'Autosportado en Polímero' },
    { value: 'AUTOSOPORTADO METALICO', label: 'Autosportado Metálico' },
    { value: 'AUTOTRANSFORMADOR', label: 'Autotransformador' },
    { value: 'AUXILIAR', label: 'Auxiliar' },
    { value: 'BALIZA', label: 'Baliza' },
    { value: 'BANDIT', label: 'Bandit' },
    { value: 'BASE ADHESIVA', label: 'Base Adhesiva' },
    { value: 'BUJE', label: 'Buje' },
    { value: 'CABEZA PILOTO', label: 'Cabeza Piloto' },
    { value: 'CABLOFIL', label: 'Cablofil' },
    { value: 'CALEFACTORA', label: 'Calefactora' },
    { value: 'CALENTADOR', label: 'Calentador' },
    { value: 'CANALETA', label: 'Canaleta' },
    { value: 'CILINDRICO', label: 'Cilíndrico' },
    { value: 'CIRCULAR', label: 'Circular' },
    { value: 'CODO', label: 'Codo' },
    { value: 'COMPACTO', label: 'Compacto' },
    { value: 'COMPATO', label: 'Compato' },
    { value: 'CONMUTADOR', label: 'Conmutador' },
    { value: 'CONTACTOS', label: 'Contactos' },
    { value: 'CONTADOR', label: 'Contador' },
    { value: 'CONTADOR DE ENERGIA', label: 'Contador de Energía' },
    { value: 'CONTAINER', label: 'Container' },
    { value: 'CONVERTIDOR', label: 'Convertidor' },
    { value: 'CONVERTIDOR/AISLADOR DE SENALES', label: 'Convertidor/Aislador de Señales' },
    { value: 'CORTACIRCUITO', label: 'Cortacircuito' },
    { value: 'CRUZ', label: 'Cruz' },
    { value: 'CUBIERTA PROTECTORA', label: 'Cubierta Protectora' },
    { value: 'CUBRELUZ', label: 'Cubre Luz' },
    { value: 'CUERPO', label: 'Cuerpo' },
    { value: 'CURVA VERTICAL AJUSTABLE', label: 'Curva Vertical Ajustable' },
    { value: 'DE ACOMETIDA', label: 'De Acometida' },
    { value: 'DE ALIMENTACION', label: 'De Alimentación' },
    { value: 'DE ALIVIO DE TENSION', label: 'De Alivio de Tensión' },
    { value: 'DE ALTA TENSION', label: 'De Alta Tensión' },
    { value: 'DE ALUMBRADO PUBLICO', label: 'De Alumbrado Público' },
    { value: 'DE BATERIAS', label: 'De Baterías' },
    { value: 'DE CELDAS DE CARGA', label: 'De Celdas de Carga' },
    { value: 'DE CHAQUETA', label: 'De Chaqueta' },
    { value: 'DE CIRCUITOS', label: 'De Circuitos' },
    { value: 'DE COBRE', label: 'De Cobre' },
    { value: 'DE COMUNICACIONES', label: 'De Comunicaciones' },
    { value: 'DE COMUNICACIONES ARMADO', label: 'De Comunicaciones Armado' },
    { value: 'DE COMUNICACIONES AUTOSOPORTADO', label: 'De Comunicaciones Autosportado' },
    { value: 'DE COMUNICACIONES DE SOBREPONER', label: 'De Comunicaciones de Sobreponer' },
    { value: 'DE CONMUTACION', label: 'De Conmutación' },
    { value: 'DE CONTACTOR', label: 'De Contactor' },
    { value: 'DE CONTACTOS', label: 'De Contactos' },
    { value: 'DE CONTROL', label: 'De Control' },
    { value: 'DE CONTROL ARMADO', label: 'De Control Armado' },
    { value: 'DE CONTROL MOTOR', label: 'De Control Motor' },
    { value: 'DE CONTROL Y POTENCIA', label: 'De Control y Potencia' },
    { value: 'DE CONTROL Y POTENCIA ARMADO', label: 'De Control y Potencia Armado' },
    { value: 'DE CORRIENTE', label: 'De Corriente' },
    { value: 'DE DERIVACION', label: 'De Derivación' },
    { value: 'DE DISTRIBUCION', label: 'De Distribución' },
    { value: 'DE DISTRIBUCION DE ALIMENTACION', label: 'De Distribución de Alimentación' },
    { value: 'DE EMERGENCIA', label: 'De Emergencia' },
    { value: 'DE ENTRADAS ANALOGICAS', label: 'De Entradas Analógicas' },
    { value: 'DE ENTRADAS DIGITALES', label: 'De Entradas Digitales' },
    { value: 'DE ENTRADAS/SALIDAS ANALOGICAS', label: 'De Entradas/Salidas Analógicas' },
    { value: 'DE ENTRADAS/SALIDAS DIGITALES', label: 'De Entradas/Salidas Digitales' },
    { value: 'DE ESTADO SOLIDO', label: 'De Estado Sólido' },
    { value: 'DE FIBRA OPTICA', label: 'De Fibra Óptica' },
    { value: 'DE FRECUENCIA', label: 'De Frecuencia' },
    { value: 'DE HORQUILLA', label: 'De Horquilla' },
    { value: 'DE IMANES PERMANENTES', label: 'De Imanes Permanentes' },
    { value: 'DE INDUCCION', label: 'De Inducción' },
    { value: 'DE INSTRUMENTACION', label: 'De Instrumentación' },
    { value: 'DE INSTRUMENTACION ARMADO', label: 'De Instrumentación Armado' },
    { value: 'DE INTERFAZ', label: 'De Interfaz' },
    { value: 'DE LINEA', label: 'De Línea' },
    { value: 'DE MANDO EN ACERO INOXIDABLE', label: 'De Mando en Acero Inoxidable' },
    { value: 'DE MANDO EN COLL-ROLLED', label: 'De Mando en Coll-Rolled' },
    { value: 'DE MANDO ESPECIAL', label: 'De Mando Especial' },
    { value: 'DE MANDO METALICA', label: 'De Mando Metálica' },
    { value: 'DE MANDO PLASTICA', label: 'De Mando Plástica' },
    { value: 'DE MANIOBRA', label: 'De Maniobra' },
    { value: 'DE MEDIA TENSION', label: 'De Media Tensión' },
    { value: 'DE MEDIA TENSION ARMADO', label: 'De Media Tensión Armado' },
    { value: 'DE MEDICION', label: 'De Medición' },
    { value: 'DE MONITOREO', label: 'De Monitoreo' },
    { value: 'DE MOTOR', label: 'De Motor' },
    { value: 'DE OJO', label: 'De Ojo' },
    { value: 'DE PASO', label: 'De Paso' },
    { value: 'DE PASO EN ACERO INOXIDABLE', label: 'De Paso en Acero Inoxidable' },
    { value: 'DE PASO EN COLL-ROLLED', label: 'De Paso en Coll-Rolled' },
    { value: 'DE PASO ESPECIAL', label: 'De Paso Especial' },
    { value: 'DE PASO METALICA', label: 'De Paso Metálica' },
    { value: 'DE PASO PLASTICA', label: 'De Paso Plástica' },
    { value: 'DE PERIFERIA', label: 'De Periferia' },
    { value: 'DE PIN', label: 'De Pin' },
    { value: 'DE POTENCIA', label: 'De Potencia' },
    { value: 'DE POTENCIA ARMADO', label: 'De Potencia Armado' },
    { value: 'DE POTENCIA FLEXIBLE', label: 'De Potencia Flexible' },
    { value: 'DE REFUERZO', label: 'De Refuerzo' },
    { value: 'DE RELUCTANCIA', label: 'De Reluctancia' },
    { value: 'DE REVESTIMIENTO', label: 'De Revestimiento' },
    { value: 'DE SALIDA EN ACERO INOXIDABLE', label: 'De Salida en Acero Inoxidable' },
    { value: 'DE SALIDA EN COLL-ROLLED', label: 'De Salida en Coll-Rolled' },
    { value: 'DE SALIDA ESPECIAL', label: 'De Salida Especial' },
    { value: 'DE SALIDA METALICA', label: 'De Salida Metálica' },
    { value: 'DE SALIDA PLASTICA', label: 'De Salida Plástica' },
    { value: 'DE SALIDAS ANALOGICAS', label: 'De Salidas Analógicas' },
    { value: 'DE SALIDAS DIGITALES', label: 'De Salidas Digitales' },
    { value: 'DE SEGURIDAD', label: 'De Seguridad' },
    { value: 'DE SELLO', label: 'De Sello' },
    { value: 'DE SENALIZACION', label: 'De Señalización' },
    { value: 'DE SENSOR', label: 'De Sensor' },
    { value: 'DE SOBRECARGA', label: 'De Sobrecarga' },
    { value: 'DE SOBREPONER A PRUEBA DE EXPLOSION', label: 'De Sobreponer a Prueba de Explosión' },
    { value: 'DE SOBREPONER EN ACERO INOXIDABLE', label: 'De Sobreponer en Acero Inoxidable' },
    { value: 'DE SOBREPONER EN COLL-ROLLED', label: 'De Sobreponer en Coll-Rolled' },
    { value: 'DE SOBREPONER EN POLIMERO', label: 'De Sobreponer en Polímero' },
    { value: 'DE SOBREPONER METALICO', label: 'De Sobreponer Metálico' },
    { value: 'DE TEMPERATURA', label: 'De Temperatura' },
    { value: 'DE TENSION', label: 'De Tensión' },
    { value: 'DE TERMINALES PREMOLDEADAS', label: 'De Terminales Premoldeadas' },
    { value: 'DE TESTEO', label: 'De Testeo' },
    { value: 'DE TIERRA', label: 'De Tierra' },
    { value: 'DE TRANFERENCIA', label: 'De Transferencia' },
    { value: 'DE TRANSFERENCIA', label: 'De Transferencia' },
    { value: 'DE UNION', label: 'De Unión' },
    { value: 'DE VARIADOR', label: 'De Variador' },
    { value: 'DESCARTABLE', label: 'Descartable' },
    { value: 'DESCONECTADOR', label: 'Desconectador' },
    { value: 'DESENGRASANTE ELECTRONICO', label: 'Desengrasante Electrónico' },
    { value: 'DESNUDO', label: 'Desnudo' },
    { value: 'DIFERENCIAL', label: 'Diferencial' },
    { value: 'DIFERENCIAL RCCB', label: 'Diferencial RCCB' },
    { value: 'DIGITAL', label: 'Digital' },
    { value: 'DIN OMEGA', label: 'Din Omega' },
    { value: 'DIRECTO', label: 'Directo' },
    { value: 'ELECTRICA', label: 'Eléctrica' },
    { value: 'ELECTROMECANICO', label: 'Electromecánico' },
    { value: 'ELECTRONICA', label: 'Electrónica' },
    { value: 'ELECTRONICO', label: 'Electrónico' },
    { value: 'EN BANCO', label: 'En Banco' },
    { value: 'EN CEMENTO', label: 'En Cemento' },
    { value: 'EN FIBRA', label: 'En Fibra' },
    { value: 'EN GABINETE', label: 'En Gabinete' },
    { value: 'EN MASILLA', label: 'En Masilla' },
    { value: 'EN PASTA', label: 'En Pasta' },
    { value: 'EN RESINA', label: 'En Resina' },
    { value: 'ESCALERA', label: 'Escalera' },
    { value: 'ESPECIAL', label: 'Especial' },
    { value: 'ESPECIAL DE COMUNICACIONES', label: 'Especial de Comunicaciones' },
    { value: 'ESPECIAL DE CONTROL', label: 'Especial de Control' },
    { value: 'ESPECIAL DE INSTRUMENTACION', label: 'Especial de Instrumentación' },
    { value: 'ESPECIAL DE PROCESO', label: 'Especial de Proceso' },
    { value: 'ESPECIAL METALICA', label: 'Especial Metálica' },
    { value: 'ESPECIAL PLASTICA', label: 'Especial Plástica' },
    { value: 'ESTANDAR', label: 'Estándar' },
    { value: 'FAST-ON', label: 'Fast-On' },
    { value: 'FINAL DE CARRERA', label: 'Final de Carrera' },
    { value: 'FIREWALL', label: 'Firewall' },
    { value: 'FLEXIBLE DE PROCESO', label: 'Flexible de Proceso' },
    { value: 'FLEXIBLE METALICA', label: 'Flexible Metálica' },
    { value: 'FLEXIBLE PLASTICA', label: 'Flexible Plástica' },
    { value: 'FOTOVOLTAICO', label: 'Fotovoltaico' },
    { value: 'FUSIBLE', label: 'Fusible' },
    { value: 'GAR', label: 'Gar' },
    { value: 'GATEWAY', label: 'Gateway' },
    { value: 'HIBRIDO', label: 'Híbrido' },
    { value: 'HIDRAULICA', label: 'Hidráulica' },
    { value: 'HIGROSTATO', label: 'Higrostato' },
    { value: 'HIGROTERMO', label: 'Higrotermo' },
    { value: 'HORNO', label: 'Horno' },
    { value: 'HORQUILLA', label: 'Horquilla' },
    { value: 'HUMEDA', label: 'Húmeda' },
    { value: 'INDUSTRIAL', label: 'Industrial' },
    { value: 'INDUSTRIAL MULTIPLE', label: 'Industrial Múltiple' },
    { value: 'INTERRUPTOR', label: 'Interruptor' },
    { value: 'INTERRUPTOR FUSIBLE', label: 'Interruptor Fusible' },
    { value: 'LAMPARA PILOTO', label: 'Lámpara Piloto' },
    { value: 'LINTERNA', label: 'Linterna' },
    { value: 'LISA', label: 'Lisa' },
    { value: 'MAGNETICO', label: 'Magnético' },
    { value: 'MALLA', label: 'Malla' },
    { value: 'MANUAL', label: 'Manual' },
    { value: 'MECANICA', label: 'Mecánica' },
    { value: 'MECANICO', label: 'Mecánico' },
    { value: 'MINERA', label: 'Minera' },
    { value: 'MINERO', label: 'Minero' },
    { value: 'MODEM', label: 'Módem' },
    { value: 'MODULAR', label: 'Modular' },
    { value: 'MODULO LED', label: 'Módulo LED' },
    { value: 'MULTIFUNCIONAL', label: 'Multifuncional' },
    { value: 'MULTIPLE', label: 'Múltiple' },
    { value: 'NEUMATICA', label: 'Neumática' },
    { value: 'NH', label: 'NH' },
    { value: 'NIPLE', label: 'Niple' },
    { value: 'OPGW', label: 'OPGW' },
    { value: 'OPTOCOPLADOR', label: 'Optoacoplador' },
    { value: 'PALA', label: 'Pala' },
    { value: 'PARA BORNERAS', label: 'Para Borneras' },
    { value: 'PARA CABLES', label: 'Para Cables' },
    { value: 'PARA COMUNICACIONES', label: 'Para Comunicaciones' },
    { value: 'PARA CONDENSADORES', label: 'Para Condensadores' },
    { value: 'PARA CONTROLADOR', label: 'Para Controlador' },
    { value: 'PARA EQUIPOS', label: 'Para Equipos' },
    { value: 'PARA FOTOVOLTAICA', label: 'Para Fotovoltaica' },
    { value: 'PARA MARCACION', label: 'Para Marcación' },
    { value: 'PARA MEDIDOR', label: 'Para Medidor' },
    { value: 'PARA MOTOR DE PASOS/PWM', label: 'Para Motor de Pasos/PWM' },
    { value: 'PARA PORTAETIQUETAS', label: 'Para Portaetiquetas' },
    { value: 'PARA POTENCIA', label: 'Para Potencia' },
    { value: 'PARA RIEL', label: 'Para Riel' },
    { value: 'PARA RIEL DIN', label: 'Para Riel DIN' },
    { value: 'PARA SENALES', label: 'Para Señales' },
    { value: 'PARA TABLERO', label: 'Para Tablero' },
    { value: 'PARO DE EMERGENCIA', label: 'Paro de Emergencia' },
    { value: 'PASAMUROS', label: 'Pasamuros' },
    { value: 'PERFIL', label: 'Perfil' },
    { value: 'PERNO', label: 'Perno' },
    { value: 'PIGTAIL', label: 'Pigtail' },
    { value: 'PLANA', label: 'Plana' },
    { value: 'PLASTICO', label: 'Plástico' },
    { value: 'PLATINA DE UNION', label: 'Platina de Unión' },
    { value: 'PLC', label: 'PLC' },
    { value: 'PORTAFUSIBLE', label: 'Portafusible' },
    { value: 'PORTATIL', label: 'Portátil' },
    { value: 'PREMOLDEADA', label: 'Premoldeada' },
    { value: 'PREMOLDEADO', label: 'Premoldeado' },
    { value: 'PRENSAESTOPA', label: 'Prensaestopa' },
    { value: 'PULSADOR', label: 'Pulsador' },
    { value: 'RACKEABLE', label: 'Rackeable' },
    { value: 'RANURADA', label: 'Ranurada' },
    { value: 'RECONECTADOR', label: 'Recontactador' },
    { value: 'REDUCCIONES TIPO CONECTOR', label: 'Reducciones Tipo Conector' },
    { value: 'REGULABLE', label: 'Regulable' },
    { value: 'REMOTA', label: 'Remota' },
    { value: 'RESETEABLE', label: 'Reseteable' },
    { value: 'RIGIDA DE PROCESO', label: 'Rígida de Proceso' },
    { value: 'RIGIDA METALICA', label: 'Rígida Metálica' },
    { value: 'RIGIDA PLASTICA', label: 'Rígida Plástica' },
    { value: 'ROUTER', label: 'Router' },
    { value: 'RTU', label: 'RTU' },
    { value: 'SACRIFICABLE', label: 'Sacrificable' },
    { value: 'SECA', label: 'Seca' },
    { value: 'SECCIONABLE', label: 'Seccionable' },
    { value: 'SECCIONADOR', label: 'Seccionador' },
    { value: 'SELECTOR', label: 'Selector' },
    { value: 'SELLO CORTAFUEGO', label: 'Sello Cortafuego' },
    { value: 'SEMICONDUCTORA', label: 'Semiconductora' },
    { value: 'SKID', label: 'Skid' },
    { value: 'SOLAR', label: 'Solar' },
    { value: 'SOPORTE', label: 'Soporte' },
    { value: 'STRUT', label: 'Strut' },
    { value: 'SUAVE', label: 'Suave' },
    { value: 'SUBMARINA', label: 'Submarina' },
    { value: 'SUJETADOR', label: 'Sujetador' },
    { value: 'SWITCH', label: 'Switch' },
    { value: 'TACTIL', label: 'Táctil' },
    { value: 'TAPA', label: 'Tapa' },
    { value: 'TAPON', label: 'Tapón' },
    { value: 'TEE', label: 'Tee' },
    { value: 'TELECOM', label: 'Telecom' },
    { value: 'TELERRUPTOR', label: 'Teleruptor' },
    { value: 'TEMPORIZADOR', label: 'Temporizador' },
    { value: 'TERMINAL EN ACERO INOXIDABLE', label: 'Terminal en Acero Inoxidable' },
    { value: 'TERMINAL EN COLL-ROLLED', label: 'Terminal en Coll-Rolled' },
    { value: 'TERMINAL ESPECIAL', label: 'Terminal Especial' },
    { value: 'TERMINAL METALICA', label: 'Terminal Metálica' },
    { value: 'TERMINAL PLASTICA', label: 'Terminal Plástica' },
    { value: 'TERMOMAGNETICO DIFERENCIAL RCBO', label: 'Termomagnético Diferencial RCBO' },
    { value: 'TERMOMAGNETICO MCB', label: 'Termomagnético MCB' },
    { value: 'TERMOSTATO', label: 'Termostato' },
    { value: 'TIPO BARRIL', label: 'Tipo Barril' },
    { value: 'TIPO BLOQUE DE DISTRIBUCION', label: 'Tipo Bloque de Distribución' },
    { value: 'TIPO CONECTOR', label: 'Tipo Conector' },
    { value: 'TIPO FUNDA', label: 'Tipo Funda' },
    { value: 'TIPO MANTA', label: 'Tipo Manta' },
    { value: 'TIPO PEINE', label: 'Tipo Peine' },
    { value: 'TIPO PORTABARRAS', label: 'Tipo Portabarras' },
    { value: 'TIPO TORRE', label: 'Tipo Torre' },
    { value: 'TIPO TUBO', label: 'Tipo Tubo' },
    { value: 'TOP JET', label: 'Top Jet' },
    { value: 'TUBULAR', label: 'Tubular' },
    { value: 'TUERCA', label: 'Tuerca' },
    { value: 'UNION', label: 'Unión' },
    { value: 'VENTILADOR', label: 'Ventilador' },
    { value: 'VFD', label: 'VFD' },
    { value: 'WYE', label: 'Wye' },
];

export default productsTypes;