const productsCategories: { value: string; label: string }[] = [
    { value: 'SIN CATEGORIA', label: 'Sin categoría' },
    { value: 'ABRAZADERA', label: 'Abrazadera' },
    { value: 'ACCESORIO PARA ABRAZADERA', label: 'Accesorio para Abrazadera' },
    { value: 'ACCESORIO PARA ACTUADOR', label: 'Accesorio para Actuador' },
    { value: 'ACCESORIO PARA AISLADOR', label: 'Accesorio para Aislador' },
    { value: 'ACCESORIO PARA AMARRE', label: 'Accesorio para Amarre' },
    { value: 'ACCESORIO PARA ARANDELA', label: 'Accesorio para Arandela' },
    { value: 'ACCESORIO PARA ARRANCADOR', label: 'Accesorio para Arrancador' },
    { value: 'ACCESORIO PARA BANDEJA', label: 'Accesorio para Bandeja' },
    { value: 'ACCESORIO PARA BANDEJA PORTACABLES', label: 'Accesorio para Bandeja Portacables' },
    { value: 'ACCESORIO PARA BARRAJE', label: 'Accesorio para Barraje' },
    { value: 'ACCESORIO PARA BATERIA', label: 'Accesorio para Batería' },
    { value: 'ACCESORIO PARA BLINDOBARRA', label: 'Accesorio para Blindobarra' },
    { value: 'ACCESORIO PARA BORNA', label: 'Accesorio para Borna' },
    { value: 'ACCESORIO PARA BORNERA', label: 'Accesorio para Bornera' },
    { value: 'ACCESORIO PARA CABLES', label: 'Accesorio para Cables' },
    { value: 'ACCESORIO PARA CAJA', label: 'Accesorio para Caja' },
    { value: 'ACCESORIO PARA CANALETA', label: 'Accesorio para Canaleta' },
    { value: 'ACCESORIO PARA CARGADOR', label: 'Accesorio para Cargador' },
    { value: 'ACCESORIO PARA CINTA', label: 'Accesorio para Cinta' },
    { value: 'ACCESORIO PARA CLAVIJA', label: 'Accesorio para Clavija' },
    { value: 'ACCESORIO PARA CONDENSADOR', label: 'Accesorio para Condensador' },
    { value: 'ACCESORIO PARA CONDULETA', label: 'Accesorio para Conduleta' },
    { value: 'ACCESORIO PARA CONECTOR', label: 'Accesorio para Conector' },
    { value: 'ACCESORIO PARA CONTACTOR', label: 'Accesorio para Contactor' },
    { value: 'ACCESORIO PARA CONTROLADOR', label: 'Accesorio para Controlador' },
    { value: 'ACCESORIO PARA DISPOSITIVO', label: 'Accesorio para Dispositivo' },
    { value: 'ACCESORIO PARA DPS', label: 'Accesorio para DPS' },
    { value: 'ACCESORIO PARA EMPALME', label: 'Accesorio para Empalme' },
    { value: 'ACCESORIO PARA ENCERRAMIENTO', label: 'Accesorio para Encerramiento' },
    { value: 'ACCESORIO PARA ENVOLVENTE', label: 'Accesorio para Envolvente' },
    { value: 'ACCESORIO PARA EQUIPO', label: 'Accesorio para Equipo' },
    { value: 'ACCESORIO PARA FIBRA OPTICA', label: 'Accesorio para Fibra Óptica' },
    { value: 'ACCESORIO PARA FUENTE', label: 'Accesorio para Fuente' },
    { value: 'ACCESORIO PARA FUSIBLE', label: 'Accesorio para Fusible' },
    { value: 'ACCESORIO PARA GENERADOR', label: 'Accesorio para Generador' },
    { value: 'ACCESORIO PARA GUARDAMOTOR', label: 'Accesorio para Guardamotor' },
    { value: 'ACCESORIO PARA HERRAMIENTA', label: 'Accesorio para Herramienta' },
    { value: 'ACCESORIO PARA HMI', label: 'Accesorio para HMI' },
    { value: 'ACCESORIO PARA IMPRESORA', label: 'Accesorio para Impresora' },
    { value: 'ACCESORIO PARA INDICADOR', label: 'Accesorio para Indicador' },
    { value: 'ACCESORIO PARA INTERRUPTOR', label: 'Accesorio para Interruptor' },
    { value: 'ACCESORIO PARA INVERSOR', label: 'Accesorio para Inversor' },
    { value: 'ACCESORIO PARA LAMPARA', label: 'Accesorio para Lámpara' },
    { value: 'ACCESORIO PARA LIMPIADOR', label: 'Accesorio para Limpiador' },
    { value: 'ACCESORIO PARA LUMINARIA', label: 'Accesorio para Luminaria' },
    { value: 'ACCESORIO PARA MANDO', label: 'Accesorio para Mando' },
    { value: 'ACCESORIO PARA MAQUINA', label: 'Accesorio para Máquina' },
    { value: 'ACCESORIO PARA MARCACION', label: 'Accesorio para Marcación' },
    { value: 'ACCESORIO PARA MEDIDOR', label: 'Accesorio para Medidor' },
    { value: 'ACCESORIO PARA MODULO', label: 'Accesorio para Módulo' },
    { value: 'ACCESORIO PARA MOTOR', label: 'Accesorio para Motor' },
    { value: 'ACCESORIO PARA PANEL SOLAR', label: 'Accesorio para Panel Solar' },
    { value: 'ACCESORIO PARA PASACABLES', label: 'Accesorio para Pasacables' },
    { value: 'ACCESORIO PARA PATCHCORD', label: 'Accesorio para Patchcord' },
    { value: 'ACCESORIO PARA PORTAFUSIBLE', label: 'Accesorio para Portafusible' },
    { value: 'ACCESORIO PARA RACK', label: 'Accesorio para Rack' },
    { value: 'ACCESORIO PARA REGULADOR', label: 'Accesorio para Regulador' },
    { value: 'ACCESORIO PARA RELE', label: 'Accesorio para Relé' },
    { value: 'ACCESORIO PARA RESISTENCIA', label: 'Accesorio para Resistencia' },
    { value: 'ACCESORIO PARA RIEL', label: 'Accesorio para Riel' },
    { value: 'ACCESORIO PARA SECCIONADOR', label: 'Accesorio para Seccionador' },
    { value: 'ACCESORIO PARA SELLANTE', label: 'Accesorio para Sellante' },
    { value: 'ACCESORIO PARA SENALIZACION', label: 'Accesorio para Señalización' },
    { value: 'ACCESORIO PARA SENSOR', label: 'Accesorio para Sensor' },
    { value: 'ACCESORIO PARA SOLDADURA', label: 'Accesorio para Soldadura' },
    { value: 'ACCESORIO PARA TABLERO', label: 'Accesorio para Tablero' },
    { value: 'ACCESORIO PARA TARJETA', label: 'Accesorio para Tarjeta' },
    { value: 'ACCESORIO PARA TERMINAL', label: 'Accesorio para Terminal' },
    { value: 'ACCESORIO PARA TERMOENCOGIBLE', label: 'Accesorio para Termoencogible' },
    { value: 'ACCESORIO PARA TOMA', label: 'Accesorio para Toma' },
    { value: 'ACCESORIO PARA TORNILLO', label: 'Accesorio para Tornillo' },
    { value: 'ACCESORIO PARA TRANSFERENCIA', label: 'Accesorio para Transferencia' },
    { value: 'ACCESORIO PARA TRANSFORMADOR', label: 'Accesorio para Transformador' },
    { value: 'ACCESORIO PARA TUBERIA', label: 'Accesorio para Tubería' },
    { value: 'ACCESORIO PARA TUERCA', label: 'Accesorio para Tuerca' },
    { value: 'ACCESORIO PARA UPS', label: 'Accesorio para UPS' },
    { value: 'ACCESORIO PARA VARIADOR', label: 'Accesorio para Variador' },
    { value: 'ACTUADOR', label: 'Actuador' },
    { value: 'AISLADOR', label: 'Aislador' },
    { value: 'AMARRE', label: 'Amarre' },
    { value: 'ARANDELA', label: 'Arandela' },
    { value: 'ARRANCADOR', label: 'Arrancador' },
    { value: 'BANDEJA PORTACABLES', label: 'Bandeja Portacables' },
    { value: 'BARRAJE', label: 'Barraje' },
    { value: 'BATERIA', label: 'Batería' },
    { value: 'BLINDOBARRA', label: 'Blindobarra' },
    { value: 'BORNA', label: 'Borna' },
    { value: 'BORNERA', label: 'Bornea' },
    { value: 'CABLE', label: 'Cable' },
    { value: 'CAJA', label: 'Caja' },
    { value: 'CANALETA', label: 'Canaleta' },
    { value: 'CARGADOR', label: 'Cargador' },
    { value: 'CINTA', label: 'Cinta' },
    { value: 'CLAVIJA', label: 'Clavija' },
    { value: 'CONDENSADOR', label: 'Condensador' },
    { value: 'CONDULETA', label: 'Conduleta' },
    { value: 'CONECTOR', label: 'Conector' },
    { value: 'CONTACTOR', label: 'Contactor' },
    { value: 'CONTROLADOR', label: 'Controlador' },
    { value: 'DISPOSITIVO', label: 'Dispositivo' },
    { value: 'DPS', label: 'DPS' },
    { value: 'EMPALME', label: 'Empalme' },
    { value: 'ENCERRAMIENTO', label: 'Encerramiento' },
    { value: 'ENVOLVENTE', label: 'Envolvente' },
    { value: 'EQUIPO', label: 'Equipo' },
    { value: 'FIBRA OPTICA', label: 'Fibra Óptica' },
    { value: 'FUENTE', label: 'Fuente' },
    { value: 'FUSIBLE', label: 'Fusible' },
    { value: 'GENERADOR', label: 'Generador' },
    { value: 'GUARDAMOTOR', label: 'Guardamotor' },
    { value: 'HERRAMIENTA', label: 'Herramienta' },
    { value: 'HMI', label: 'HMI' },
    { value: 'IMPRESORA', label: 'Impresora' },
    { value: 'INDICADOR', label: 'Indicador' },
    { value: 'INTERRUPTOR', label: 'Interruptor' },
    { value: 'INVERSOR', label: 'Inversor' },
    { value: 'LAMPARA', label: 'Lámpara' },
    { value: 'LIMPIADOR', label: 'Limpiador' },
    { value: 'LUMINARIA', label: 'Luminaria' },
    { value: 'MANDO', label: 'Mando' },
    { value: 'MAQUINA', label: 'Máquina' },
    { value: 'MARCACION', label: 'Marcación' },
    { value: 'MEDIDOR', label: 'Medidor' },
    { value: 'MODULO', label: 'Módulo' },
    { value: 'MOTOR', label: 'Motor' },
    { value: 'PANEL SOLAR', label: 'Panel Solar' },
    { value: 'PASACABLES', label: 'Pasacables' },
    { value: 'PATCHCORD', label: 'Patchcord' },
    { value: 'PORTAFUSIBLE', label: 'Portafusible' },
    { value: 'RACK', label: 'Rack' },
    { value: 'REGULADOR', label: 'Regulador' },
    { value: 'RELE', label: 'Relé' },
    { value: 'RESISTENCIA', label: 'Resistencia' },
    { value: 'RIEL', label: 'Riel' },
    { value: 'SECCIONADOR', label: 'Seccionador' },
    { value: 'SELLANTE', label: 'Sellante' },
    { value: 'SENALIZACION', label: 'Señalización' },
    { value: 'SENSOR', label: 'Sensor' },
    { value: 'SOLDADURA', label: 'Soldadura' },
    { value: 'TABLERO', label: 'Tablero' },
    { value: 'TARJETA', label: 'Tarjeta' },
    { value: 'TERMINAL', label: 'Terminal' },
    { value: 'TERMOENCOGIBLE', label: 'Termoencogible' },
    { value: 'TOMA', label: 'Toma' },
    { value: 'TORNILLO', label: 'Tornillo' },
    { value: 'TRANSFERENCIA', label: 'Transferencia' },
    { value: 'TRANSFORMADOR', label: 'Transformador' },
    { value: 'TUBERIA', label: 'Tubería' },
    { value: 'TUERCA', label: 'Tuerca' },
    { value: 'UPS', label: 'UPS' },
    { value: 'VARIADOR', label: 'Variador' },
];

export default productsCategories;